### ISSUE TITLE
Joinedload for generic relationships

### ISSUE THREAD

**Issue by anishrav** [kvesteri/sqlalchemy-utils#626] opened 2022-07-20 21:45 UTC
It seems like there's some talk of `batch_fetch` supporting this, but I don't see `batch_fetch` anywhere in this repo.

Is there a way to eagerly load generic relationships? Right now the default is `lazy` which emits too many database queries.

**Comment by anishrav** [comment] 2022-07-20 21:46
@kurtmckee any chance you can take a look at this?

**Comment by anishrav** [comment] 2022-07-20 21:46
#299 has had no activity on it for a year

**Comment by kurtmckee** [comment] 2022-07-20 22:02
I don't know how to do this, and I can't commit to reviewing it at this time.

Closing as a duplicate of #299.

**Closed by kurtmckee** 2022-07-20 22:02 UTC
