### ISSUE TITLE
Schema information is neglected by create_view

### ISSUE THREAD

**Issue by fhoehle** [kvesteri/sqlalchemy-utils#441] opened 2020-04-30 13:41 UTC
Thanks for this handy toolbox @kvesteri !
How would you include schema names into [`create_view`](https://github.com/kvesteri/sqlalchemy-utils/blob/master/sqlalchemy_utils/view.py#L119)? Should it be called with `create_view("testSchema.myView")`? This will neglect the camel case notation and yields error.
At the moment I "fixed" this behavior by using the [`table`](https://github.com/kvesteri/sqlalchemy-utils/blob/master/sqlalchemy_utils/view.py#L155) objects in [`CreateView`](https://github.com/kvesteri/sqlalchemy-utils/blob/master/sqlalchemy_utils/view.py#L13)

**Comment by sachitrajbhandari** [comment] 2021-04-09 05:36
@fhoehle, could you share your solution how you were able to specify the schema while creating view?

**Comment by nestguti** [comment] 2022-04-14 10:15
Duplicate of #427

**Closed** 2022-04-16 19:14 UTC

**Comment by quotquot** [comment] 2023-11-20 19:41
I am surprised this is closed. I am using version 0.41.0 from Debian and the schema is still ignored. Running:

```python
from sqlalchemy import create_mock_engine
from sqlalchemy import MetaData, select
from sqlalchemy_utils import create_view

def dump(sql, *multiparams, **params):
    code = str(sql.compile(dialect=engine.dialect)).strip()
    print(f"{code};\n")

metadata = MetaData(schema="foo")
view = create_view("bar", select(1), metadata)
engine = create_mock_engine("postgresql://localhost", dump)
metadata.create_all(engine)
```
will print:
```
CREATE VIEW bar AS SELECT 1;
```
I believe it should print:
```
CREATE VIEW foo.bar AS SELECT 1;
```
